### ISSUE TITLE
Issue with 2011-01.facts.txt and 2011-01.convs.txt

### ISSUE THREAD

**Issue by hk-bmi** [qkaren/converse_reading_cmr#2]
I just wanted to confirm if there is a problem with the 2011-01.facts.txt

```
tail 2011-01.facts.txt 

d3bdad23db2f763b5900e744042eeeab986fcb8a7e512a8bd01f98d3	anime	fcila	en.wikipedia.org	edit links
0eb9a3a98e1c088aea0088cad81fe75f9fe5e9027a2ef43e0b713dc0	anime	fcila	en.wikipedia.org	this page was last modified on 9 july 2014 at 23:39 .
5f0815aed9570ac8ce01f3b0c53fdc556acda013bbd65c69ec898e33	anime	fcila	en.wikipedia.org	text is available under the creative commons attribution-sharealike license ;
5a0f466076447e4ac0c10adfb55dba20f8fa7a46ccde0ac05069cf24	anime	fcila	en.wikipedia.org	additional terms may apply . by using this site , you agree to the terms of use and privacy policy . wikipedia ® is a registered trademark of the wikimedia foundation , inc . , a non-profit organization .
b73419fac4f0da8b7c8f2daeb6ec6d830fe3a1ab216398ddfdf2a4cb	anime	fcila	en.wikipedia.org	privacy policy
84517e056d7357f0d6c2fba2fd4346c4c6f6b04350d84b483effa673	anime	fcila	en.wikipedia.org	about wikipedia
b353e48bb4cbfae87b7afb6eeec40ccd5797e5d232f5700307b8034a	anime	fcila	en.wikipedia.org	disclaimers
4119685eed94884b3b2650270a25772caa34a713548a6c9abcbd4acd	anime	fcila	en.wikipedia.org	contact wikipedia
958b25cf6c30360f971e3328f35e0bedb7770c03b080bc7a774a89b1	anime	fcila	en.wikipedia.org	developers
10467c4a49a59539fd2087399d0684815a6f9cac331f0ab7360b2205	anime	fcila	en.wikipedia.org	mobile view

```

As you can see, in the above 10 facts, the fact  is either `privacy policy`, `about wikipedia`, `disclaimer` - these are not facts in true sense. it is some random information. Kindly clarify.

**Comment by qkaren** [comment]
As explained in the readme, we keep all the output of the html-to-text converter, even though some of it tends to be rather noisy (because some text comes from tables, buttons, etc. and doesn't form full sentences). However, important html tags (e.g.,`<p>`, `<tilte>`) are kept. "As some of the fact data tend to be noisy, you may want to restrict yourself to facts delimited by these tags." There is good data (between `<p>`, etc) and bad data (for completeness, so that the entire text of the page is there.) If you don't want the bad data, you can just ignore it.
